return validationerror if password len <= 16
GeekZoneHQ/web pull request #42
Opened 2020-10-03 13:49 UTC by jamesgeddes

Minimum length requirement done. 

Need to recaptcha. Will split into its own issue.

2020-10-03 14:21 UTC, CarwynNelson commented
It looks like Django has this built in and might be slightly more robust https://docs.djangoproject.com/en/3.0/topics/auth/passwords/#password-validation

Also, whilst 16 characters would be ideal there are many folks who might find remembering creating and remembering a password that long quite hard.

We could (and should) push people towards password managers, but maybe we should mention a few options instead of just lastpass? Maybe some FOSS options that aren't tied to a proprietary service?

2020-10-03 15:00 UTC, jamesgeddes commented
We need to avoid complexity rules, so should just stick to length requirements. Always in favour of FOSS, but Lastpass will pay GZ for every paid account we refer.

2020-10-03 15:01 UTC, jamesgeddes commented
Have not looked at the automated testing. Will have a look.

2020-10-04 11:08 UTC, jamesgeddes commented
Password now requires min of 10 chars, just because its an easy round number. Once we release, we can put a link to the GZ password manager blog post in the registration form, but it's not obligatory for MVP.

2020-10-04 11:53 UTC, jamesgeddes commented
updated automated tests with a permissible password. Should we do a test that checks to see if bad passwords are rejected?

2020-10-04 11:57 UTC, CarwynNelson commented
> Should we do a test that checks to see if bad passwords are rejected?

Absolutely :)

2020-10-04 12:00 UTC, CarwynNelson requested changes
Could we add that extra test for passwords that are too short, plus a few small changes that I have noted in the review.

Overall this looks great :)

2020-10-04 12:01 UTC, CarwynNelson commented
Also this test is now failing:
```
FAIL: test_signed_in_users_cannot_register (memberships.tests.test_registration_form.RegisterFormTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/circleci/project/memberships/tests/test_registration_form.py", line 26, in test_signed_in_users_cannot_register
    self.assertEqual(response.status_code, 403)
AssertionError: 200 != 403
```

2020-10-04 12:32 UTC, jamesgeddes commented on memberships/forms.py
> +        # raise forms.ValidationError(mark_safe('Use a <a href="http://example.com" target="_blank">'
Oops! Yes, on it now

2020-10-04 12:37 UTC, jamesgeddes commented on web/settings.py
> +            "user_attributes": (
specifies which elements should be checked for similarity

2020-10-04 12:46 UTC, jamesgeddes commented
> Also this test is now failing:
> 
> ```
> FAIL: test_signed_in_users_cannot_register (memberships.tests.test_registration_form.RegisterFormTestCase)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/circleci/project/memberships/tests/test_registration_form.py", line 26, in test_signed_in_users_cannot_register
>     self.assertEqual(response.status_code, 403)
> AssertionError: 200 != 403
> ```

I have updated the password in `test_signed_in_users_cannot_register` so that it provides a permissible password.

2020-10-04 13:01 UTC, CarwynNelson commented on web/settings.py
> +            "user_attributes": (
It seems to me that all of these fields are likely to be similar. What does a value of 0.5 mean?

2020-10-04 14:41 UTC, CarwynNelson approved these changes

2020-10-04 14:41 UTC, merged