Cookie banner and cookie consent (#24)
GeekZoneHQ/web pull request #59
Opened 2020-10-21 13:06 UTC by giulio-giunta

Hi guys, 
please check my work.
Giulio

2020-10-21 15:55 UTC, jamesgeddes commented on web/settings.py
> +                    "description": _("Matomo cookie for website analysis."),
Are we using Matomo now?

2020-10-21 16:41 UTC, Freshrojek commented
Hey James!
I'm not sure sorry I haven't done anything to do with the cookies yet, I'm
gonna work on the recaptcha more tonight.
See you soon,
Jack


On Wed, Oct 21, 2020, 16:55 James Geddes <notifications@github.com> wrote:

> *@jamesgeddes* commented on this pull request.
> ------------------------------
>
> In web/settings.py
> <https://github.com/GeekZoneHQ/web/pull/59#discussion_r509406761>:
>
> > +                    "description": _("This cookie prevents Cross-Site-Request-Forgery attacks."),
> +                },
> +                {
> +                    "pattern": "sessionid",
> +                    "description": _("This cookie is necessary to allow logging in, for example."),
> +                },
> +            ],
> +        },
> +        {
> +            "id": "analytics",
> +            "name": _("Analytics"),
> +            "optional": True,
> +            "cookies": [
> +                {
> +                    "pattern": "_pk_.*",
> +                    "description": _("Matomo cookie for website analysis."),
>
> Are we using Matomo now?
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/GeekZoneHQ/web/pull/59#pullrequestreview-513843740>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARKNTPQ3I3C6RJOTNBWC563SL3777ANCNFSM4SZYFX3A>
> .
>

2020-10-21 18:48 UTC, CarwynNelson requested changes
I have pulled this down on to my local machine and I did not get a cookie prompt, which makes sense as there have been no changes to the templates.

It seems that the docs for this library are not very good as it does not mention that we need to include a few extra things in a base template to get this working. The docs also neglect to mention a dependency on `jquery` and `jquery-modal` which I am not a fan of at all.

I managed to get this running locally and I will detail the steps if you are interested to see it working, but after some further research I think we would be better off doing the cookie consent banner ourselves. This is not as scary as it might seem, and I'm more than happy to provide you with guidance to help you get it implemented (there are several avenues we can take).

In order to get this running locally:
1. Add `{% load cookiebanner %}` after line 1 in `memberships/templates/base.html`
2. Add the following after the main css file is loaded in that same base.html
```html
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha256-4+XzXVhsDmqanXGHaHvgh1gMQKX40OUvDEBTu8JcmNs=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.css" />
```
3. After the body tag in that same template file add `{% cookiebanner_modal %}`

After doing that and running the django development server you should be presented with something like this on first page load.

![image](https://user-images.githubusercontent.com/3310215/96768706-0b648c00-13d6-11eb-97f1-0a82a61db38f.png)

2020-10-22 08:14 UTC, jamesgeddes commented
> I'm not sure sorry I haven't done anything to do with the cookies yet, I'm

This is a request to review the code that @giulio-giunta has submitted, so you would take a look and add any comments you feel necessary :)

2020-11-15 15:12 UTC, jamesgeddes commented
Closed by mistake, soz @giulio-giunta !

2020-11-18 20:05 UTC, giulio-giunta commented
Hi guys, 
I adapted the cookie banner and removed a lot of stuff to best fit it in the page. I was not able to make work the buttons to save and accept cookies. Sorry!!!
I will need some help for that as it involves JavaScript. If possible I would like to assist who fixes it so I can understand the logic. 
Many thanks.
Giulio

2022-05-08 08:33 UTC, closed without merging